# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingitem',
            old_name='item',
            new_name='name',
        ),
    ]
